### PR TITLE
visual

### PR DESCRIPTION
**Pull request by ivanko22**

### CODE REVIEW

**Comment by ivanko22** [comment]
@MorganLee909 please review my last commit

**Comment by MorganLee909** [comment]
1. Above 1650px screen width (approximately), items are not centered in box.
    2. Below 800px screen width (approximately), right side of box moves towards and then through items.
    3. Jeopardy.ejs
        1. Line 1:  Why did you remove <!DOCTYPE html> ?
        2. Lines 7 + 21:  I want this to remain as JEOPARDY!  “Let’s play Jeopardy game” is actually incorrect English.
        3. Line 21:  “class=tittle” same typo in css.  Not a big deal, but should be fixed anyway.
        4. Lines 70 + 76:  You have extra tags in there. (h1)
    4. Click on ‘How To’ leaves the start button over the instructions.
    5. My version works ok on mobile, yours only on widescreen, such as desktop computers.  I would like to have this work on both.
    6. Can you make the game larger?  This will most often be used in classrooms with projectors, so I would like the game to be as large as possible.
    7. Please, please format  jeopardy.ejs.  Things are not aligned.  Seems like a small thing, but it makes reading everything so much easier.  Some tags are not aligned where they should be, indents aren’t always correct, etc.

**Comment by MorganLee909** [comment]
Also, you removed the efl.ejs page.  I understand and it looks good.  However, the menu item still says EFL and also, what is your plan when I add more games?  I had that EFL page because I am soon going to add more games and that is the place where you can choose your game.

**Comment by ivanko22** [comment]
> Also, you removed the efl.ejs page. I understand and it looks good. However, the menu item still says EFL and also, what is your plan when I add more games? I had that EFL page because I am soon going to add more games and that is the place where you can choose your game.

I think it will be good to show these games as cards.

**Comment by ivanko22** [comment]
> ```
> 1. Above 1650px screen width (approximately), items are not centered in box.
> 2. Below 800px screen width (approximately), right side of box moves towards and then through items.
> 3. Jeopardy.ejs
>     1. Line 1:  Why did you remove <!DOCTYPE html> ?
>     2. Lines 7 + 21:  I want this to remain as JEOPARDY!  “Let’s play Jeopardy game” is actually incorrect English.
>     3. Line 21:  “class=tittle” same typo in css.  Not a big deal, but should be fixed anyway.
>     4. Lines 70 + 76:  You have extra tags in there. (h1)
> 4. Click on ‘How To’ leaves the start button over the instructions.
> 5. My version works ok on mobile, yours only on widescreen, such as desktop computers.  I would like to have this work on both.
> 6. Can you make the game larger?  This will most often be used in classrooms with projectors, so I would like the game to be as large as possible.
> 7. Please, please format  jeopardy.ejs.  Things are not aligned.  Seems like a small thing, but it makes reading everything so much easier.  Some tags are not aligned where they should be, indents aren’t always correct, etc.
> ```

I know there are a lot of bugs. It is the first version. I think is better to see some feedback as earlier as possible. Will work on it.

**Comment by ivanko22** [comment]
@MorganLee909 check new pull request please

**Comment by MorganLee909** [comment]
The button is not working because it is not connected to anything.  the 'onclick=...' calls a js function.  You have no js in the file.  You need to write the function startBtn(button).  Couple other minor things:
1.  "Start" on the first start button isn't vertically centered for some reason.
2.  "content-title" not "content-tittle"
3.  Please format everything so that it looks good.  I am talking mostly about the efl.css file.  There is already a section for the efl.css file there.  Put your css for that page under that and remove anything that isn't used.  You can always create subsections inside efl if you need to.

I love the way it looks by the way, truly amazing, thanks a lot.  Also, you can remove the extra cards since I only have the one for now.  I understand how to create more once I have another game or something else.  

Also, I can do all or some of this for you if you want.  It's your code and if you want to practice doing it then that's ok, but I can help or do some of it for you if you want, just let me know.

**Comment by MorganLee909** [comment]
Love it man, great job on everything.  Thanks a lot.

**Comment by ivanko22** [comment]
My pleasure, You are welcome :)

**Pull request merged**
